# This is a basic workflow to help you get started with Actions

name: 自动push防止Actions自动停止

# Controls when the workflow will run
on:
    workflow_dispatch:
    schedule:
        - cron: '* * */59 * *'
    repository_dispatch:
        types: start_action


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: bcanseco/github-contribution-graph-action@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GIT_EMAIL: myself@xiaokunji.com 
            GIT_COMMIT_MESSAGE: 自动激活action

